on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools setuptools_scm wheel
          sudo apt-get install flex bison
      - name: Build Yosys for WASM
        run: |
          ./build_yosys.sh
      - name: Build nmigen-yosys binary wheels
        run: |
          python setup.py bdist_wheel
      - name: Upload binary wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/
  upload_wheels:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wheel
        path: dist/
    - name: Publish packages to Test PyPI
      if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_token }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish packages to PyPI
      if: github.event_name == 'push' && github.event.ref == 'refs/heads/release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
