on:
  schedule:
    - cron: '0 0 * * *'
name: Track wasmtime releases
jobs:
  track-wasmtime:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Check for a new release and update version requirement
        id: track-version
        run: |
          pip install git+https://github.com/whitequark/track-pypi-dependency-version.git
          track-pypi-dependency-version --status $GITHUB_OUTPUT -r dependencies.txt wasmtime
      - name: Install dependencies
        if: steps.track-version.outputs.status == 'stale'
        run: |
          python -m pip install setuptools_scm # for setup.py --version
          sudo apt-get install flex bison ccache
      - name: Set up caching
        if: steps.track-version.outputs.status == 'stale'
        uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-
      - name: Build WASM binaries
        if: steps.track-version.outputs.status == 'stale'
        run: |
          ./build.sh
      - name: Test against updated version requirement
        if: steps.track-version.outputs.status == 'stale'
        run: |
          pip install .
          python -m amaranth_yosys --help
      - name: Push updated version requirement
        if: steps.track-version.outputs.status == 'stale'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            [autorelease] Update wasmtime version requirement from ${{ steps.track-version.outputs.old-requirement }} to ${{ steps.track-version.outputs.new-requirement }}.
